###########################################################
#HOW OFTEN SHOULD WE SAVE THE CONFIG FILES IN MINUTES?    #
#WE ALSO HANDLE SERVER CRASHES/RESTARTS/RELOADS NO WORRIES#
###########################################################
config-save-intervals: 10

########################
#ALLOW ONE PERSON SLEEP#
########################
is-sleeping-ignored: true

#########################
#ALLOW ENDERMAN GRIEFING#
#########################
enderman-griefing: false

#########################################################
#ALLOW SPECIAL PERMISSIONS TO SPECIFIED RANKS############
#SET THESE PERMISSIONS BELOW, IN THE PERMISSIONS SECTION#
#########################################################
special-permissions: true

########################################################
#SET SPECIAL PERMISSIONS FOR ACCESS OUT SIDE ADMIN MODE#
#THIS CAN BE BYPASSED //babysitter.bypass.special\\#####
########################################################
special-permissions-always: false

#####################################################
#ALLOW ADMIN TO USE CREATIVE#########################
#THIS CAN BE BYPASSED //babysitter.bypass.creative\\#
#####################################################
allow-creative: true

###################################################
#ALLOW ADMIN FLIGHT IN SURVIVAL####################
#THIS CAN BE BYPASSED //babysitter.bypass.flight\\#
###################################################
admin-survial-flight: false

#################################################
#CAN AN ADMIN /GIVE TO ADMINS IN SURVIVAL?#######
#REQUIRES GIVE PERMISSION IS SET TO TRUE#########
#THIS CAN BE BYPASSED //babysitter.bypass.give\\#
#################################################
admin-to-admin-give: false

#################################################
#DISABLE GIVE COMMAND############################
#REQUIRES GIVE PERMISSION IS SET TO TRUE#########
#THIS CAN BE BYPASSED //babysitter.bypass.give\\#
#################################################
allow-give: true

#################################################
#FORCE ADMIN TO PLAYER IN SPECTATOR##############
#THIS CAN BE BYPASSED //babysitter.bypass.spec\\#
#################################################
force-spectate: false

##########################################################
#SET THIS TO CONTROL BLOCKS PLACED BY ADMINS, YOU CAN SET#
#THESE ITEMS BELOW, REFER TO THE WIKI FOR A FULL LIST#####
##########################################################
safe-blocks-to-place: true

##########################################################
#SET THIS TO CONTROL ITEMS DROPPED BY ADMINS, YOU CAN SET#
#THESE ITEMS BELOW, REFER TO THE WIKI FOR A FULL LIST#####
##########################################################
safe-items-to-drop: true

#######################################################
#SPECIAL RANK NAME(s)##################################
#PLEASE NOTE LUCKPERMS REQUIRES IT TO BE ALL LOWERCASE#
#######################################################
special-ranks:
  - owner

#######################################################
#ADMIN RANK NAME(s)####################################
#PLEASE NOTE LUCKPERMS REQUIRES IT TO BE ALL LOWERCASE#
#######################################################
admin-ranks:
  - admin
  - owner

#############
#SAFE BLOCKS#
#############
safe-blocks:
  - CRAFTING_TABLE
  - FURNACE
  - ANVIL
  - DIRT
  - SAND
  - COBBLESTONE
  - STONE
  - OAK_SIGN
  - ACACIA_SIGN
  - SPRUCE_SIGN
  - BIRCH_SIGN
  - DARK_OAK_SIGN
  - JUNGLE_SIGN
  - OAK_BOAT
  - ACACIA_BOAT
  - SPRUCE_BOAT
  - BIRCH_BOAT
  - DARK_OAK_BOAT
  - JUNGLE_BOAT
  - TORCH
  - BARRIER
  - BONE_MEAL
  - BEDROCK
  - DRAGON_EGG
  - GRASS_BLOCK
  - LADDER
  - MAP
  - BAMOBOO_SAPLING
  - OAK_SAPLING
  - ACACIA_SAPLING
  - SPRUCE_SAPLING
  - BIRCH_SAPLING
  - DARK_OAK_SAPLING
  - JUNGLE_SAPLING
  - BLACK_BED
  - WHITE_BED
  - ORANGE_BED
  - MAGENTA_BED
  - LIGHT_BLUE_BED
  - YELLOW_BED
  - LIME_BED
  - PINK_BED
  - LIGHT_GRAY_BED
  - GRAY_BED
  - CYAN_BED
  - PURPLE_BED
  - BLUE_BED
  - BROWN_BED
  - GREEN_BED
  - RED_BED

###################################################
#PERMISSIONS SECTION###############################
#YOU MAY ADD ANY PERMISSION, FROM ANY PLUGIN HERE!#
#JUST MAKE SURE TO ONLY USE SPACES, NOT TAB, AND###
#FOLLOW THE EXACT SAME LAYOUT. NO LIMIT!###########
#THIS CAN BE BYPASSED //babysitter.bypass.perms\\##
###################################################
#<permission reference number>:                   #
#     <permission>: essentials.command.home       #
#     <value>: true/false                         #
###################################################

#########################################################
#SPECIAL PERMISSION LIST#################################
#THESE WILL EVALUATE AFTER ADMIN PERMISSIONS#############
#ALLOWING THEM TO OVERWRITE DATA FROM ADMIN PERMISSIONS##
#THIS CAN BE BYPASSED //babysitter.bypass.specialperms\\#
#########################################################
special-permissions-list:
  1:
    permission: minecraft.command.setblock
    value: true
  2:
    permission: minecraft.command.seed
    value: true
  3:
    permission: minecraft.command.selector
    value: true

#ADMIN PERMISSION LIST#
admin-permissions-list:
  1:
    permission: babysitter.command.see
    value: true
  2:
    permission: babysitter.command.edit
    value: true
  3:
    permission: minecraft.command.teleport
    value: true
  4:
    permission: babysitter.command.give
    value: true
  5:
    permission: minecraft.command.gamemode
    value: true
  6:
    permission: minecraft.command.effect
    value: true
  7:
    permission: minecraft.command.selector
    value: false
