name: BabySitter
version: ${project.version}
main: th3doc.babysitter.Main
api-version: 1.13
authors: [Th3_DoC]
description: Admin Plugin

commands:
  babysit:
    description: Activate Admin State.
    aliases: [bs]
    permission: babysitter.command.bs
  vanish:
    description: Toggle Vanish State.
    permission: babysitter.command.vanish
  god:
    description: Toggle God Mode.
    permission: babysitter.command.god
  fly:
    description: Toggle Fly Mode.
    permission: babysitter.command.fly
  see:
    description: View/Edit Player Inventories.
    permission: babysitter.command.see
  back:
    description: Travel Back To Your Survival Location.
    permission: babysitter.bypass.tp
  give:
    description: Give Players Minecraft Items
    permission: babysitter.command.give

permissions:
  babysit.*:
    description: Allow All Permissions.
    default: op
    children:
      babysitter.command.*:
        description: Allow All Commands.
        default: op
        children:
          babysitter.command.bs:
            description: Allows The Use Of BabySit Command.
            default: op
          babysitter.command.vanish:
            description: Allows The Use Of Vanish Command.
            default: op
          babysitter.command.fly:
            description: Allows The Use Of Hide Command.
            default: op
          babysitter.command.god:
            description: Allows The Use Of God Command.
            default: op
          babysitter.command.see:
            description: Allows The Use Of InvSee Command.
            default: op
          babysitter.command.edit:
            description: Allows The Editing of Players.
            default: op
          babysitter.command.give:
            description: Allows Give Function Without Selector Capabilities.
            default: false
      babysitter.bypass.*:
        description: Bypass Admin Restrictions.
        default: op
        children:
          babysitter.bypass.spec:
            description: Bypass forced Spectator Mode.
            default: op
          babysitter.bypass.give:
            description: Bypass Configs /Give cancel.
            default: op
          babysitter.bypass.tp:
            description: Bypass TP Controls & Restrictions.
            default: op
          babysitter.bypass.creative:
            description: Bypass Disabled Creative.
            default: op
          babysitter.bypass.perms:
            description: Bypass Config Set Permission Changes. Note That Permissions Set To False In The Config Will Not Change A True Value!
            default: op
          babysitter.bypass.flight:
            description: Allows Flight in Survival.
            default: op
          babysitter.bypass.special:
            description: Special Permissions Will Always Be Active.
            default: op
          babysitter.bypass.specialperms:
            description: Bypass Config Set Permission Changes. Note That Permissions Set To False In The Config Will Not Change A True Value!
            default: op
          babysitter.bypass.inv:
            description: Bypass Inventory Changes.
            default: op
          babysitter.bypass.see:
            description: Bypass See Target Block.
            default: op
          babysitter.bypass.vanish:
            description: Bypass Forced Vanish Toggle.
            default: op
          babysitter.bypass.blocks:
            description: Bypass Blocked Block Placement.
            default: op
          babysitter.bypass.item:
            description: Bypass Blocked Item Drops.
            default: op
  babysitter.admin.*:
    description:
    default: false
    children:
      babysitter.admin.op:
        desciption: Allows All Babysitter Permissions Without The Player Being OP.
        children:
          babysitter.command.*: true
          babysitter.bypass.*: true
      babysitter.admin.trusted:
        description: Allows Most BabySitter Properties, Refer To The Wiki.
        children:
          babysitter.command.bs: true
          babysitter.command.vanish: true
          babysitter.command.fly: true
          babysitter.command.god: true
          babysitter.command.see: true
          babysitter.command.edit: true
          babysitter.command.give: true
          babysitter.bypass.spec: true
          babysitter.bypass.give: true
          babysitter.bypass.tp: false
